# Generated by Django 3.2.9 on 2021-11-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistermodel',
            old_name='id_cards',
            new_name='id_card',
        ),
    ]
