# Generated by Django 3.2.9 on 2021-11-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_id_cards_userregistermodel_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddMedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=18)),
                ('description', models.TextField(max_length=200)),
                ('expiry_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='Prod_images/')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('available_stock', models.IntegerField(default=18)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.addcategorymodel')),
            ],
        ),
    ]
