# Generated by Django 3.2.9 on 2021-11-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_addcategorymodel_addmedicinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmedicinemodel',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
