# Generated by Django 3.2.9 on 2021-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_addmedicinemodel_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
