# Generated by Django 3.2.9 on 2021-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
