# Generated by Django 3.2.9 on 2021-12-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_addcartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcartmodel',
            name='address',
            field=models.TextField(default='none', max_length=100),
        ),
    ]
